default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres  # PostgreSQLのユーザー名に変更
  password: cyoko@9981  # 必要に応じてパスワードを設定
  host: localhost  # ローカルで使用する場合は'localhost'、リモートの場合はホスト名やIPアドレスに変更

development:
  <<: *default
  database: myapp_development
  host: localhost  # ::1からlocalhostに変更


test:
  <<: *default
  database: myapp_test  # テスト用データベース名を指定

production:
  <<: *default
  database: myapp_production  # 本番用データベース名を指定
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>  # 環境変数からユーザー名を取得
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>  # 環境変数からパスワードを取得
  host: <%= ENV['MYAPP_DATABASE_HOST'] %>  # 環境変数からホスト名を取得
  port: <%= ENV['MYAPP_DATABASE_PORT'] || 5432 %>  # ポートを環境変数から、デフォルトは5432
  url: <%= ENV['DATABASE_URL'] %>  # DATABASE_URLを環境変数から取得
